// ── shader/builder.rs ─────────────────────────────────────────────────────────
//
// `ShaderBuilder` assembles a complete, valid WGSL compute shader from:
//   1. `CellSchema`      – the `struct Cell { … }` and zero-initialiser.
//   2. `Topology`        – neighbour count, optional inline `get_neighbor` WGSL.
//   3. `CompiledRule`    – per-cell rule body (uses `read_cell()` / `get_neighbor()`).
//
// Three modes:
//   Standard – bindings 0-2 (cells_current, cells_next, neighbor_table).
//              `get_neighbor` reads from the table.
//   Inline   – bindings 0-1 (cells_current, cells_next). No neighbor_table.
//              `get_neighbor` is provided by the topology.
//   Chunked  – bindings 0-3 (cells_current, cells_next, boundary, chunk_params).
//              `get_neighbor` is chunked-aware (returns tagged boundary indices).
//              `read_cell` dispatches between own cells and boundary buffer.

use super::templates::WORKGROUP_SIZE;
use crate::cell::schema::CellSchema;
use crate::rule_graph::compiler::CompiledRule;
use crate::shader::templates::SPARSE_ACTIVATE_FN;

/// 2-D dispatch constant: max threads in X = 65535 * WORKGROUP_SIZE.
const DISPATCH_X_SIZE: u64 = 65535 * WORKGROUP_SIZE as u64;

/// Parameters needed to emit the compute shader.
pub struct ShaderBuilder<'a> {
    pub schema: &'a CellSchema,
    pub neighbor_count: usize,
    pub rule: &'a CompiledRule,
    pub sparse: bool,
    pub topology_name: &'a str,
    pub cell_count: usize,
    /// Topology-generated WGSL for `fn get_neighbor` (inline / non-chunked).
    pub neighbor_fn: Option<String>,
    /// Topology-generated WGSL for `fn get_neighbor` (chunked mode).
    pub chunked_neighbor_fn: Option<String>,
    /// Whether to emit chunked bindings.
    pub chunked: bool,
}

impl<'a> ShaderBuilder<'a> {
    /// Build the standard or inline-neighbour compute shader.
    pub fn build(&self) -> String {
        let mut src = String::with_capacity(4096);

        // ── Header ────────────────────────────────────────────────────────
        src.push_str(&format!(
            "// AUTO-GENERATED by gpu-automata ShaderBuilder\n\
             // Topology   : {}\n\
             // Cell count : {}\n\
             // Neighbors  : {}\n\
             // Sparse     : {}\n\
             // Inline nbr : {}\n\n",
            self.topology_name,
            self.cell_count,
            self.neighbor_count,
            self.sparse,
            self.neighbor_fn.is_some(),
        ));

        // ── Cell struct ───────────────────────────────────────────────────
        src.push_str(&self.schema.generate_wgsl_struct());
        src.push('\n');

        // ── Constants ─────────────────────────────────────────────────────
        src.push_str(&format!(
            "const NEIGHBOR_COUNT: u32 = {}u;\n",
            self.neighbor_count,
        ));
        src.push_str(&format!("const DISPATCH_X_SIZE: u32 = {}u;\n\n", DISPATCH_X_SIZE));

        // ── Storage bindings ──────────────────────────────────────────────
        src.push_str(
            "@group(0) @binding(0) var<storage, read>       cells_current: array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(1) var<storage, read_write> cells_next:    array<Cell>;\n",
        );

        let has_inline = self.neighbor_fn.is_some();
        if !has_inline {
            src.push_str(
                "@group(0) @binding(2) var<storage, read>       neighbor_table: array<u32>;\n",
            );
        }

        if self.sparse {
            src.push_str(
                "@group(0) @binding(3) var<storage, read>       active_cells:      array<u32>;\n",
            );
            src.push_str(
                "@group(0) @binding(4) var<storage, read_write> next_active_cells: array<u32>;\n",
            );
            src.push_str(
                "@group(0) @binding(5) var<storage, read_write> next_active_count: array<atomic<u32>>;\n",
            );
            src.push('\n');
            src.push_str(SPARSE_ACTIVATE_FN);
        }
        src.push('\n');

        // ── get_neighbor / read_cell ──────────────────────────────────────
        if let Some(ref nbr_fn) = self.neighbor_fn {
            src.push_str(nbr_fn);
        } else {
            // Table-based fallback
            src.push_str("fn get_neighbor(cell_index: u32, slot: u32) -> u32 {\n");
            src.push_str("    return neighbor_table[cell_index * NEIGHBOR_COUNT + slot];\n");
            src.push_str("}\n");
        }
        src.push('\n');
        src.push_str("fn read_cell(idx: u32) -> Cell {\n");
        src.push_str("    return cells_current[idx];\n");
        src.push_str("}\n\n");

        // ── Compute entry point ───────────────────────────────────────────
        src.push_str(&format!(
            "@compute @workgroup_size({}, 1, 1)\n\
             fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
            WORKGROUP_SIZE,
        ));
        src.push_str("    let cell_index: u32 = gid.x + gid.y * DISPATCH_X_SIZE;\n");

        if self.sparse {
            src.push_str("    if (cell_index >= arrayLength(&active_cells)) { return; }\n");
            src.push_str("    let real_index: u32 = active_cells[cell_index];\n");
            // Use real_index as cell_index from here – rename for the rule body
            src.push_str("    let self_cell: Cell = cells_current[real_index];\n");
            src.push_str("    var result_cell: Cell = self_cell;\n");
            src.push_str(&self.rule.wgsl_body);
            src.push_str("    cells_next[real_index] = result_cell;\n");
            src.push_str(
                "\n    for (var _si: u32 = 0u; _si < NEIGHBOR_COUNT; _si++) {\n\
                     let _snb: u32 = get_neighbor(real_index, _si);\n\
                     if (_snb != 0xFFFFFFFFu) { activate_cell(_snb); }\n\
                 }\n\
                 activate_cell(real_index);\n",
            );
        } else {
            src.push_str("    if (cell_index >= arrayLength(&cells_current)) { return; }\n");
            src.push_str("    let self_cell: Cell = cells_current[cell_index];\n");
            src.push_str("    var result_cell: Cell = self_cell;\n");
            src.push_str(&self.rule.wgsl_body);
            src.push_str("    cells_next[cell_index] = result_cell;\n");
        }

        src.push_str("}\n");
        src
    }

    /// Build the chunked compute shader (per-chunk bindings + boundary).
    pub fn build_chunked(&self) -> String {
        let mut src = String::with_capacity(4096);

        src.push_str(&format!(
            "// AUTO-GENERATED chunked compute shader\n\
             // Topology : {}\n\
             // Neighbors: {}\n\n",
            self.topology_name, self.neighbor_count,
        ));

        // Cell struct
        src.push_str(&self.schema.generate_wgsl_struct());
        src.push('\n');

        // ChunkParams uniform
        src.push_str("struct ChunkParams {\n");
        src.push_str("    strip_h:    u32,\n");
        src.push_str("    strip_y0:   u32,\n");
        src.push_str("    own_count:  u32,\n");
        src.push_str("    _pad:       u32,\n");
        src.push_str("}\n\n");

        // Constants
        src.push_str(&format!(
            "const NEIGHBOR_COUNT: u32 = {}u;\n",
            self.neighbor_count,
        ));
        src.push_str(&format!("const DISPATCH_X_SIZE: u32 = {}u;\n\n", DISPATCH_X_SIZE));

        // Bindings
        src.push_str(
            "@group(0) @binding(0) var<storage, read>       cells_current: array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(1) var<storage, read_write> cells_next:    array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(2) var<storage, read>       boundary:      array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(3) var<uniform>             chunk_params:  ChunkParams;\n\n",
        );

        // get_neighbor (chunked, topology-provided)
        if let Some(ref nbr_fn) = self.chunked_neighbor_fn {
            src.push_str(nbr_fn);
        }
        src.push('\n');

        // read_cell: dispatches between own cells and boundary
        src.push_str("fn read_cell(idx: u32) -> Cell {\n");
        src.push_str("    if ((idx & 0x80000000u) != 0u) {\n");
        src.push_str("        return boundary[idx & 0x7FFFFFFFu];\n");
        src.push_str("    }\n");
        src.push_str("    return cells_current[idx];\n");
        src.push_str("}\n\n");

        // Entry point
        src.push_str(&format!(
            "@compute @workgroup_size({}, 1, 1)\n\
             fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
            WORKGROUP_SIZE,
        ));
        src.push_str("    let cell_index: u32 = gid.x + gid.y * DISPATCH_X_SIZE;\n");
        src.push_str("    if (cell_index >= chunk_params.own_count) { return; }\n");
        src.push_str("    let self_cell: Cell = cells_current[cell_index];\n");
        src.push_str("    var result_cell: Cell = self_cell;\n");
        src.push_str(&self.rule.wgsl_body);
        src.push_str("    cells_next[cell_index] = result_cell;\n");
        src.push_str("}\n");
        src
    }

    // ── Render shader ─────────────────────────────────────────────────────

    /// Generate a render shader that colours cells by a named scalar field.
    ///
    /// The vertex shader uses `instance_index` as cell index and positions a
    /// unit quad at the appropriate grid location.  The fragment shader maps
    /// the field value (clamped to [0,1]) through a colour ramp.
    pub fn build_render_shader(schema: &CellSchema, color_field: &str) -> String {
        use crate::shader::templates::{RENDER_FRAG, RENDER_VERT_PREAMBLE};
        // Note: grid_width/grid_height are passed to the shader at runtime
        // via the RenderUniforms uniform buffer, not baked into the WGSL source.

        let mut src = String::new();
        src.push_str("// AUTO-GENERATED render shader\n\n");
        src.push_str(&schema.generate_wgsl_struct());
        src.push('\n');
        src.push_str("@group(0) @binding(0) var<storage, read> cells: array<Cell>;\n");
        src.push_str(RENDER_VERT_PREAMBLE);
        src.push('\n');

        // Vertex shader
        src.push_str(concat!(
            "@vertex\n",
            "fn vs_main(\n",
            "    @builtin(vertex_index)   vert_idx: u32,\n",
            "    @builtin(instance_index) inst_idx: u32,\n",
            ") -> VertexOutput {\n",
            "    let cell: Cell = cells[inst_idx];\n",
            "\n",
        ));

        // Cell value extraction (cast field to f32)
        let field_ty = schema.field_type(color_field);
        let field_expr = match field_ty {
            Some(crate::cell::field::FieldType::F32) => format!("cell.{}", color_field),
            _ => format!("f32(cell.{})", color_field),
        };

        // Vertex shader body using CameraUniforms.
        // cell_w / cell_h already encode zoom and aspect-ratio correction so
        // every cell is square on screen regardless of window dimensions.
        src.push_str(&format!(
            // Each cell is a unit quad scaled by cell_w × cell_h.
            // Grid row 0 is at the bottom (standard math / NDC orientation).
            "    let cell_value: f32 = {field};
             
             // Decode instance → 2-D grid position
             let gw = camera.grid_w;
             let cx = f32(inst_idx % gw);
             let cy = f32(inst_idx / gw);
             
             // World offset from camera centre (in grid-cell units)
             let wx = cx + 0.5 - camera.cam_x;
             let wy = cy + 0.5 - camera.cam_y;
             
             // NDC position
             let quad = QUAD_VERTS[vert_idx % 6u];
             let pos  = vec2<f32>(
                 wx * camera.cell_w + quad.x * camera.cell_w,
                 wy * camera.cell_h + quad.y * camera.cell_h,
             );
             
             var out: VertexOutput;
             out.position   = vec4<f32>(pos, 0.0, 1.0);
             out.cell_value = cell_value;
             return out;
             }}

",
            field = field_expr,
        ));

        src.push_str(RENDER_FRAG);
        src
    }
}
