// ── shader/builder.rs ─────────────────────────────────────────────────────────
//
// `ShaderBuilder` is the single place that assembles a complete, valid WGSL
// compute shader.  It is constructed from the three independent parts of the
// simulation description:
//
//   1. `CellSchema`   – the generated `struct Cell { … }` and zero-initialiser.
//   2. `Topology`     – the `NEIGHBOR_COUNT` constant.
//   3. `CompiledRule` – the inner body of the per-cell rule.
//
// Optionally it can include the sparse-update bindings.
//
// The output is a single `String` ready to be passed to
// `wgpu::Device::create_shader_module`.
//
// Binding layout (group 0)
// ────────────────────────
//   0  cells_current   – read-only storage
//   1  cells_next      – read-write storage
//   2  neighbor_table  – read-only storage
//   3  active_cells    – read-only storage   (sparse mode only)
//   4  next_active_cells – read-write storage (sparse mode only)
//   5  next_active_count – read-write atomic  (sparse mode only)

use super::templates::WORKGROUP_SIZE;
use crate::cell::schema::CellSchema;
use crate::rule_graph::compiler::CompiledRule;
use crate::shader::templates::SPARSE_ACTIVATE_FN;

/// Parameters needed to emit the compute shader.
pub struct ShaderBuilder<'a> {
    pub schema: &'a CellSchema,
    pub neighbor_count: usize,
    pub rule: &'a CompiledRule,
    pub sparse: bool,
    pub topology_name: &'a str,
    pub cell_count: usize,
}

impl<'a> ShaderBuilder<'a> {
    /// Build and return the full WGSL source text.
    pub fn build(&self) -> String {
        let mut src = String::with_capacity(4096);

        // ── Header comment ────────────────────────────────────────────────
        src.push_str(&format!(
            "// AUTO-GENERATED by gpu-automata ShaderBuilder\n\
             // Topology   : {topo}\n\
             // Cell count : {cc}\n\
             // Neighbors  : {nc}\n\
             // Sparse     : {sparse}\n\n",
            topo = self.topology_name,
            cc = self.cell_count,
            nc = self.neighbor_count,
            sparse = self.sparse,
        ));

        // ── Cell struct ───────────────────────────────────────────────────
        src.push_str("// ── Cell struct ─────────────────────────────────────────────────\n");
        src.push_str(&self.schema.generate_wgsl_struct());
        src.push('\n');

        // ── Constants ─────────────────────────────────────────────────────
        src.push_str("// ── Constants ───────────────────────────────────────────────────\n");
        src.push_str(&format!(
            "const NEIGHBOR_COUNT: u32 = {}u;\n\n",
            self.neighbor_count
        ));

        // ── Storage bindings ──────────────────────────────────────────────
        src.push_str("// ── Storage bindings ────────────────────────────────────────────\n");
        src.push_str(
            "@group(0) @binding(0) var<storage, read>       cells_current:   array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(1) var<storage, read_write> cells_next:      array<Cell>;\n",
        );
        src.push_str(
            "@group(0) @binding(2) var<storage, read>       neighbor_table:  array<u32>;\n",
        );

        if self.sparse {
            src.push_str(
                "@group(0) @binding(3) var<storage, read>         active_cells:      array<u32>;\n",
            );
            src.push_str(
                "@group(0) @binding(4) var<storage, read_write>   next_active_cells: array<u32>;\n",
            );
            src.push_str("@group(0) @binding(5) var<storage, read_write>   next_active_count: array<atomic<u32>>;\n");
            src.push('\n');
            src.push_str(SPARSE_ACTIVATE_FN);
        }

        src.push('\n');

        // ── Compute entry point ───────────────────────────────────────────
        src.push_str("// ── Compute entry point ─────────────────────────────────────────\n");
        src.push_str(&format!(
            "@compute @workgroup_size({ws}, 1, 1)\nfn main(@builtin(global_invocation_id) gid: vec3<u32>) {{\n",
            ws = WORKGROUP_SIZE,
        ));

        if self.sparse {
            // In sparse mode the global id indexes into `active_cells`, not the full grid.
            src.push_str(
                "    let active_idx: u32 = gid.x;\n\
                     if (active_idx >= arrayLength(&active_cells)) { return; }\n\
                     let cell_index: u32 = active_cells[active_idx];\n",
            );
        } else {
            src.push_str(
                "    let cell_index: u32 = gid.x;\n\
                     if (cell_index >= arrayLength(&cells_current)) { return; }\n",
            );
        }

        // Initialise result from current cell (copy-on-write semantics)
        src.push_str(&format!(
            "    let self_cell: Cell = cells_current[cell_index];\n\
             \n\
             // result_cell starts as a copy; the rule may override any fields.\n\
             var result_cell: Cell = self_cell;\n\
             \n\
             // ── Rule graph body ──────────────────────────────────────────\n\
             {rule_body}\n",
            rule_body = self.rule.wgsl_body,
        ));

        // Write result
        src.push_str("    cells_next[cell_index] = result_cell;\n");

        // In sparse mode, propagate activity to neighbours
        if self.sparse {
            src.push_str(
                "\n    // Activate all neighbours of this cell for the next step.\n\
                 for (var _si: u32 = 0u; _si < NEIGHBOR_COUNT; _si++) {\n\
                     let _snb: u32 = neighbor_table[cell_index * NEIGHBOR_COUNT + _si];\n\
                     if (_snb != 0xFFFFFFFFu) { activate_cell(_snb); }\n\
                 }\n\
                 activate_cell(cell_index);\n",
            );
        }

        src.push_str("}\n");
        src
    }

    // ── Render shader ─────────────────────────────────────────────────────

    /// Generate a render shader that colours cells by a named scalar field.
    ///
    /// The vertex shader uses `instance_index` as cell index and positions a
    /// unit quad at the appropriate grid location.  The fragment shader maps
    /// the field value (clamped to [0,1]) through a colour ramp.
    pub fn build_render_shader(schema: &CellSchema, color_field: &str) -> String {
        use crate::shader::templates::{RENDER_FRAG, RENDER_VERT_PREAMBLE};
        // Note: grid_width/grid_height are passed to the shader at runtime
        // via the RenderUniforms uniform buffer, not baked into the WGSL source.

        let mut src = String::new();
        src.push_str("// AUTO-GENERATED render shader\n\n");
        src.push_str(&schema.generate_wgsl_struct());
        src.push('\n');
        src.push_str("@group(0) @binding(0) var<storage, read> cells: array<Cell>;\n");
        src.push_str(RENDER_VERT_PREAMBLE);
        src.push('\n');

        // Vertex shader
        src.push_str(concat!(
            "@vertex\n",
            "fn vs_main(\n",
            "    @builtin(vertex_index)   vert_idx: u32,\n",
            "    @builtin(instance_index) inst_idx: u32,\n",
            ") -> VertexOutput {\n",
            "    let gw: u32   = uniforms.grid_width;\n",
            "    let gh: u32   = uniforms.grid_height;\n",
            "    let cell: Cell = cells[inst_idx];\n",
            "\n",
        ));

        // Cell value extraction (cast field to f32)
        let field_ty = schema.field_type(color_field);
        let field_expr = match field_ty {
            Some(crate::cell::field::FieldType::F32) => format!("cell.{}", color_field),
            _ => format!("f32(cell.{})", color_field),
        };

        // Build vertex shader body with explicit newlines for clean WGSL.
        // vert_idx is always 0..5 (we draw 6 vertices per instance) so
        // indexing QUAD_VERTS with it is safe; the % 6u is belt-and-braces.
        src.push_str(&format!(
            "    let cell_value: f32 = {field} * uniforms.field_scale;\n\
             \n    // Map instance index to 2-D grid position\n\
             \n    let cx: u32 = inst_idx % gw;\
             \n    let cy: u32 = inst_idx / gw;\
             \n    let cell_size_x: f32 = 2.0f / f32(gw);\
             \n    let cell_size_y: f32 = 2.0f / f32(gh);\
             \n    let center_x: f32 = -1.0f + (f32(cx) + 0.5f) * cell_size_x;\
             \n    let center_y: f32 = -1.0f + (f32(cy) + 0.5f) * cell_size_y;\
             \n    let quad: vec2<f32> = QUAD_VERTS[vert_idx % 6u];\
             \n    let pos: vec2<f32> = vec2<f32>(\
             \n        center_x + quad.x * cell_size_x,\
             \n        center_y + quad.y * cell_size_y,\
             \n    );\
             \n    var out: VertexOutput;\
             \n    out.position   = vec4<f32>(pos, 0.0f, 1.0f);\
             \n    out.cell_value = cell_value;\
             \n    return out;\
             \n}}\n\n",
            field = field_expr,
        ));

        src.push_str(RENDER_FRAG);
        src
    }
}
